engine:
  defaults:
    book: 2
    author: 2

spring:
  datasource:
    spring:
      datasource: url:jdbc:h2:mem:testdb
      initialization-mode:  always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

    show-sql: true
logging:
  level:
    ROOT: INFO

server:
  port: 8082