drop table author if exists;
drop table note_category if exists;
drop table note if exists;
drop table note_book if exists;

create table author (
id bigint generated by default as identity,
name varchar(255) not null,
password varchar(255) not null,
primary key (id)
);

create table category (
id bigint generated by default as identity,
name varchar(255) not null,
primary key (id)
);

create table note (
id bigint generated by default as identity,
text varchar(255) not null,
primary key (id),
author_id bigint,
book_id bigint
);

create table book (
id bigint generated by default as identity,
name varchar(255) not null,
primary key (id)
);

create table note_categories (
note_id bigint not null,
category_id bigint not null
);

alter table author
    add constraint nc1 unique (name);

alter table category
    add constraint nc2 unique (name);

alter table note
    add constraint nc3 unique (text);

alter table book
    add constraint nc4 unique (name);

alter table note
    add constraint FKdhrwbbwlcy35n6avchj4nao51
        foreign key (author_id)
            references author;

alter table note
    add constraint FKrvvxymn6mnvx141furq7gp6kf
        foreign key (book_id)
            references book;

alter table note_categories
    add constraint FK532lngablu67p8cvv4t9xo0hf
        foreign key (category_id)
            references category;

alter table note_categories
    add constraint FKhcww7iekjxfyx52qh26c7p8lt
        foreign key (note_id)
            references note;

