version: '3'
services:
  pgdb:
    container_name: pgdb
    restart: always
    image: postgres:13
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=springp
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pgdb
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: snation
    restart: unless-stopped

  tgnotesagent:
    build: .
    depends_on:
      - pgdb
    privileged: true
    ports:
      - "8090:8085"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/springp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - TGNA_BOT_TOKEN1=${TGNA_BOT_TOKEN1}
    restart: unless-stopped
